### PR TITLE
fix windows compile errors

### LINKED ISSUE #1: Couldn't install on Windows by pip
I couldn't install it by pip on windows, and received the error messages below;

  error: command 'C:\\Users\\XXX\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

If somebody suggest me, it would be great helpful!
Hiro

### PR DESCRIPTION
**Pull request by xiongyihui**
fix #1

### CODE REVIEW

**Comment by wiseman** [comment]
Awesome, thanks, @xiongyihui!  I should be able to merge that today.

**Comment by wiseman** [comment]
Merged.  Thanks, @xiongyihui, and I gave you commit access since it's slow for me to do Windows development.

**Comment by wiseman** [comment]
I pushed version 2.0.8 to pypi which should have your fixes.

**Comment by btbulxb** [comment]
sorry, would please to show me how to use it? Thank you so much

**Pull request merged**
